"""
Script to generate the products.js file for The Botanical Bazaar storefront.

This script reads an Excel inventory file and produces a JavaScript file
containing an array of product objects compatible with the existing site.

Usage:
    python generate_products.py [input.xlsx] [output.js]

Input:
    The Excel workbook must contain a worksheet with a header row. The
    script attempts to automatically detect column names based on common
    labels (e.g. "Name", "Price", "Description", "Zones", "Quantity",
    "Image", "Category", "For Sale", "Notes"). Only rows where the
    "For Sale" column has a value of "Y" (case‑insensitive) will be
    included in the output. Rows marked otherwise are considered not for
    sale and are filtered out.

Output:
    A JavaScript file beginning with `window.PRODUCTS = [` and ending with
    `];` containing one object literal per product. Each product includes
    slug, name, image, sizes, type, description, price, quantity, zones,
    categories and optionally a `collectorSpecs` field derived from the
    inventory notes.

Zone Handling:
    USDA hardiness zones below 3 are removed entirely. If a zone range
    spans below 3, the starting zone is coerced to 3. For example,
    "1-5" becomes ["3", "4", "5"]. Any zones above 13 are capped at 13.

Slug Generation:
    Product slugs are generated by lower‑casing the product name,
    replacing whitespace and punctuation with hyphens and removing
    invalid characters. Multiple consecutive hyphens are collapsed into
    one. Trailing hyphens are trimmed.

Collector Specs:
    If a row contains a column labelled "Notes" (case‑insensitive), its
    contents are mapped into a `collectorSpecs` array on the product. The
    text is split on semicolons or line breaks to produce discrete specs.

Dependencies:
    This script requires the pandas library. If pandas is not installed,
    you can install it with `pip install pandas openpyxl`.
"""

import sys
import re
from pathlib import Path
from typing import List, Dict, Any

try:
    import pandas as pd
except ImportError as e:
    raise SystemExit("Error: pandas is required to run this script. Install it with 'pip install pandas openpyxl' and try again.")


def slugify(text: str) -> str:
    """Convert a string into a URL‑friendly slug."""
    text = text.lower().strip()
    # Replace apostrophes and ampersands with hyphenated equivalents
    text = text.replace("'", "").replace("&", "and")
    # Replace non‑alphanumeric characters with hyphens
    text = re.sub(r"[^a-z0-9]+", "-", text)
    # Collapse multiple hyphens
    text = re.sub(r"-+", "-", text)
    # Strip leading/trailing hyphens
    return text.strip("-")


def parse_zones(zone_value: Any) -> List[str]:
    """
    Given a zone string or number, return a list of zone strings between
    min_zone and max_zone inclusive. Zones are coerced to the range 3–13.
    The input may be a single number (e.g. 9), a string like "9", "9-11",
    "9b", "5a" or a comma-separated list such as "3,4,5".
    """
    if zone_value is None or pd.isna(zone_value):
        return []
    zone_str = str(zone_value).strip()
    # Replace spaces and semicolons with commas
    zone_str = zone_str.replace(";", ",").replace(" ", ",")
    # Support range notation like 3-9 or 3a-9b. Remove trailing letters
    zones: List[str] = []
    for part in zone_str.split(","):
        part = part.strip()
        if not part:
            continue
        # Remove zone letters (a/b) for numeric handling
        part_clean = re.sub(r"[a-zA-Z]", "", part)
        if '-' in part_clean:
            start, end = part_clean.split('-')
            try:
                start_int = int(float(start))
                end_int = int(float(end))
            except ValueError:
                continue
            if start_int > end_int:
                start_int, end_int = end_int, start_int
            # Coerce to allowed range 3–13
            for z in range(max(3, start_int), min(13, end_int) + 1):
                zones.append(str(z))
        else:
            try:
                z = int(float(part_clean))
                if 3 <= z <= 13:
                    zones.append(str(z))
            except ValueError:
                continue
    # Deduplicate and sort as strings
    return sorted(set(zones), key=lambda x: int(x))


def detect_column(df: pd.DataFrame, names: List[str]) -> str:
    """Find a column in df matching any of the provided names (case‑insensitive)."""
    for name in names:
        for col in df.columns:
            if col.strip().lower() == name.lower():
                return col
    return ""


def build_product_object(row: pd.Series, colmap: Dict[str, str]) -> Dict[str, Any]:
    """Construct a product dictionary from a DataFrame row using column mapping."""
    name = str(row[colmap['name']]).strip()
    slug = slugify(name)
    # Determine image path; default to placeholder if missing
    image = row.get(colmap['image'], '')
    image_path = str(image).strip() if image and not pd.isna(image) else 'assets/placeholder.png'
    # Derive size information
    sizes_val = row.get(colmap['sizes'], '')
    sizes = str(sizes_val).strip() if sizes_val and not pd.isna(sizes_val) else ''
    # Type/category
    type_val = row.get(colmap['type'], '')
    plant_type = str(type_val).strip() if type_val and not pd.isna(type_val) else 'Plant'
    # Description
    desc_val = row.get(colmap['description'], '')
    description = str(desc_val).strip() if desc_val and not pd.isna(desc_val) else ''
    # Price
    price_val = row.get(colmap['price'], 0)
    try:
        price = float(price_val)
    except (ValueError, TypeError):
        price = 0.0
    # Quantity
    qty_val = row.get(colmap['quantity'], 0)
    try:
        quantity = int(float(qty_val))
    except (ValueError, TypeError):
        quantity = 0
    # Zones
    zones_val = row.get(colmap['zones'], '')
    zones_list = parse_zones(zones_val)
    # Categories
    cats_val = row.get(colmap['categories'], '')
    if cats_val and not pd.isna(cats_val):
        if isinstance(cats_val, str):
            categories = [c.strip().lower().replace(' ', '-') for c in re.split(r",|;", cats_val) if c.strip()]
        else:
            categories = [str(c).strip().lower().replace(' ', '-') for c in cats_val if str(c).strip()]
    else:
        categories = ['other']
    # Collector specs from notes, split into bullet points
    specs = []
    notes_val = row.get(colmap['notes'], '')
    if notes_val and not pd.isna(notes_val):
        # Split notes on semicolons or newlines
        parts = re.split(r"[;\n]", str(notes_val))
        for p in parts:
            p = p.strip()
            if p:
                specs.append(p)

    product: Dict[str, Any] = {
        'slug': slug,
        'name': name,
        'image': image_path,
        'sizes': sizes,
        'type': plant_type,
        'description': description,
        'price': round(price, 2),
        'quantity': quantity,
        'zones': zones_list,
        'categories': categories
    }
    if specs:
        product['collectorSpecs'] = specs
    return product


def main(input_path: str, output_path: str) -> None:
    # Read the Excel workbook
    df = pd.read_excel(input_path, engine='openpyxl')
    # Detect column names
    colmap: Dict[str, str] = {}
    colmap['name'] = detect_column(df, ['name', 'product name', 'common name', 'scientific name']) or df.columns[0]
    colmap['price'] = detect_column(df, ['price', 'cost'])
    colmap['quantity'] = detect_column(df, ['quantity', 'qty', 'stock'])
    colmap['zones'] = detect_column(df, ['zones', 'zone', 'hardiness zones', 'hardiness'])
    colmap['sizes'] = detect_column(df, ['sizes', 'size', 'pot size', 'container size'])
    colmap['type'] = detect_column(df, ['type', 'category', 'plant type'])
    colmap['categories'] = detect_column(df, ['categories', 'tags']) or colmap['type']
    colmap['description'] = detect_column(df, ['description', 'desc', 'summary'])
    colmap['image'] = detect_column(df, ['image', 'img', 'photo', 'filename', 'image file'])
    colmap['for_sale'] = detect_column(df, ['for sale', 'available', 'sell'])
    colmap['notes'] = detect_column(df, ['notes', 'collector specs', 'specs', 'comments'])

    # Filter rows based on For Sale column
    if colmap['for_sale']:
        sale_mask = df[colmap['for_sale']].astype(str).str.strip().str.upper() == 'Y'
        df_filtered = df[sale_mask].copy()
    else:
        df_filtered = df.copy()

    products: List[Dict[str, Any]] = []
    for _, row in df_filtered.iterrows():
        product = build_product_object(row, colmap)
        products.append(product)

    # Write the output JavaScript file
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('window.PRODUCTS = [\n')
        for idx, product in enumerate(products):
            # Convert Python dict to JSON string with proper formatting
            import json
            json_str = json.dumps(product, ensure_ascii=False, indent=2)
            # Indent each line by two spaces for readability
            lines = ["  " + line for line in json_str.splitlines()]
            f.write("\n".join(lines))
            if idx < len(products) - 1:
                f.write(',\n')
            else:
                f.write('\n')
        f.write('];\n')
    print(f"Wrote {len(products)} products to {output_path}")


if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("Usage: python generate_products.py <input.xlsx> [output.js]")
        sys.exit(1)
    input_file = sys.argv[1]
    out_file = sys.argv[2] if len(sys.argv) > 2 else 'products.js'
    input_path = Path(input_file)
    output_path = Path(out_file)
    if not input_path.is_file():
        print(f"Error: input file {input_path} does not exist.")
        sys.exit(1)
    main(str(input_path), str(output_path))